//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMastery.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchoolMastery.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap graphPic_Image {
            get {
                object obj = ResourceManager.GetObject("graphPic.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US History
        ///History
        ///0
        ///q=How many United States Armed Forces do we have?
        ///a2=2
        ///a3=3
        ///a4=4
        ///a5=5
        ///c=4
        ///qh=On what day do we celebrate Independence Day?
        ///t= Ask your parents
        ///s= You can look it up in any calendar
        ///a1=June 18
        ///a2=July 14
        ///a3=September 9
        ///a4=July 4
        ///c=4
        ///q=What is the flower of New York?
        ///a1=Dandelion
        ///a2=Daisy
        ///a3=Rose
        ///a4=Carnation
        ///c=2
        ///qh=On what day do we celebrate Independence Day?
        ///t= Ask your parents
        ///s= You can look it up in any calendar
        ///a1=June 18
        ///a2=July 14
        ///a3=September 9
        ///a4=Ju [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KHistoryOne {
            get {
                return ResourceManager.GetString("KHistoryOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition
        ///Math
        ///0
        ///q=2+2=?
        ///a1=1
        ///a2=2
        ///a3=3
        ///a4=4
        ///c=4
        ///qh=3+5=?
        ///t= You can start at five and count 3 times
        ///s= 5 + 1 = 6, 5 + 2 = 7, 5 + 3 = ?
        ///a1=8
        ///a2=12
        ///a3=5
        ///a4=3
        ///c=1
        ///q=4+5=?
        ///a1=7
        ///a2=9
        ///a3=12
        ///a4=10
        ///c=2
        ///qh=3+5=?
        ///t= You can start at five and count 3 times
        ///s= 5 + 1 = 6, 5 + 2 = 7, 5 + 3 = ?
        ///a1=8
        ///a2=12
        ///a3=5
        ///a4=3
        ///c=1.
        /// </summary>
        internal static string KMathOne {
            get {
                return ResourceManager.GetString("KMathOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication
        ///Math
        ///0
        ///q=2*2=?
        ///a1=1
        ///a2=2
        ///a3=3
        ///a4=4
        ///c=4
        ///qh=3*5=?
        ///t= You can add 3 together five times
        ///s= 3 + 3 + 3 + 3 + 3 = ?
        ///a1=8
        ///a2=15
        ///a3=18
        ///a4=12
        ///c=2
        ///q=4*5=?
        ///a1=7
        ///a2=20
        ///a3=12
        ///a4=10
        ///c=2
        ///qh=3*5=?
        ///t= You can add 3 together five times
        ///s= 3 + 3 + 3 + 3 + 3 = ?
        ///a1=8
        ///a2=15
        ///a3=18
        ///a4=12
        ///c=2.
        /// </summary>
        internal static string KMathTwo {
            get {
                return ResourceManager.GetString("KMathTwo", resourceCulture);
            }
        }
    }
}
